base: 
    allmodule: True
    tool:
        base_readQuery: True
        base_writeQuery: True
        base_tableDDL: True
        base_databaseList: True
        base_tableList: True
        base_columnDescription: True
        base_tablePreview: False
        base_tableAffinity: False
        base_tableUsage: False
    prompt:
        base_query: True
        base_tableBusinessDesc: False
        base_databaseBusinessDesc: False

dba:
    allmodule: False
    tool:
        dba_userSqlList: True
        dba_tableSqlList: True
        dba_tableSpace: True
        dba_databaseSpace: True
        dba_databaseVersion: True
        dba_resusageSummary: True
        dba_resusageUserSummary: True
        dba_flowControl: True
        dba_featureUsage: True
        dba_userDelay: True
        dba_tableUsageImpact: True
        dba_sessionInfo: True
    prompt:
        dba_databaseHealthAssessment: True
        dba_userActivityAnalysis: True
        dba_tableArchive: True
        dba_databaseLineage: True
        dba_tableDropImpact: True

qlty:
    allmodule: False
    tool:
        qlty_missingValues: True
        qlty_negativeValues: True
        qlty_distinctCategories: True
        qlty_standardDeviation: True
        qlty_columnSummary: True
        qlty_univariateStatistics: True
        qlty_rowsWithMissingValues: True
    prompt:
        qlty_databaseQuality: True 

rag:
    allmodule: False
    tool:
        rag_executeWorkflow: True
    prompt:
        rag_guidelines: False 

sql_clustering:
    allmodule: True
    tool:
        sql_clustering_executeFullPipeline: True
        sql_clustering_analyzeClusterStats: True
        sql_clustering_retrieveClusterQueries: True
    prompt:
        sql_clustering_optimizationGuidelines: True

customer:
    allmodule: True
    tool:
        customer_meetingPrep: True
    prompt:
        customer_meetingStrategy: True

financial_reports:
    allmodule: True
    tool:
        financial_rag_analysis: True
    prompt:
        financial_analysis_guidelines: True

sec:
    allmodule: False
    tool:
        sec_userDbPermissions: True
        sec_rolePermissions: True
        sec_userRoles: True
    prompt:

evs:
    allmodule: False
    tool:
    prompt:    

fs: 
    allmodule: False
    tool:
        fs_reconnect_to_database: True
        fs_setFeatureStoreConfig: True
        fs_getFeatureStoreConfig: True
        fs_isFeatureStorePresent: True
        fs_featureStoreContent: True
        fs_getDataDomains: True
        fs_getFeatures: True
        fs_getAvailableDatasets: True
        fs_getFeatureDataModel: True
        fs_getAvailableEntities: True
        fs_createDataset: True
    prompt:

cust:
    allmodule: False
    tool:
    prompt: