# RAG Configuration File

# RAG Version Selection
version: 'byom'  # Options: 'byom' (ONNXEmbeddings) or 'ivsm' (IVSM functions)

# Database Configuration
databases:
  query_db: "demo_db"
  model_db: "demo_db"
  vector_db: "demo_db"

# Table Configuration
tables:
  query_table: "user_query"
  query_embedding_store: "user_query_embeddings"
  vector_table: "pdf_embeddings_store"
  model_table: "embeddings_models"
  tokenizer_table: "embeddings_tokenizers"

# Model Configuration
model:
  model_id: "bge-small-en-v1.5"

# RAG Retrieval Configuration
retrieval:
  default_k: 10  # Default number of chunks to retrieve
  max_k: 50      # Maximum allowed chunks (safety limit)

# Vector Store Schema Configuration
vector_store_schema:
  # Required fields (always present in every vector store)
  required_fields:
    - "txt"           
  
  # Specify the metadata fields available in YOUR chunked/embedded vector store table
  # (These are the columns in your vector store table beyond 'txt' and the embedding columns)
  # Only list fields that actually exist in your vector store table
  metadata_fields_in_vector_store:
    - "chunk_num"
    - "page_num"
    - "doc_name"
    # Add any other metadata columns from your vector store table here
    # Examples: "page_num", "chapter", "chunk_token_length", "author", etc.

# Embedding Configuration
embedding:
  vector_length: 384
  vector_column_prefix: "emb_"
  distance_measure: "cosine"
  feature_columns: "[emb_0:emb_383]"