all:
  tool:
    - .*
  prompt:
    - ^(?!test_).*
  resource:
    - .*

tester:
  tool:
    - .*
  prompt:
    - .*
  resource:
    - .*

dba:
  tool:
    - ^dba_*
    - ^base_*
    - ^sec_*
  prompt:
    - ^dba_*

dataScientist:
  tool:
    - ^base_*
    # - ^rag_*
    - ^sql_*
    - ^custom_* 
    # - ^Customer_* 
    # - ^Financial_*
    - ^cx_*
    - ^complaint_*
    - ^customer_*
    - ^banking_*
    # - ^fs_*
    # - ^qlty_*
    # - ^sec_userDbPermissions
    # - ^dba_userSqlList
  prompt:
    - ^rag_*
    - ^sql_*

eda:
  tool:
    - "base_(?!(writeQuery|dynamicQuery)$).*"
    - qlty_.*
    - sec_userDbPermissions